# Generated by Django 4.2.5 on 2023-10-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='priority',
            new_name='Priority',
        ),
    ]
