# Generated by Django 4.2.5 on 2023-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0005_alter_todo_priority_alter_todo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
        migrations.AlterField(
            model_name='todo',
            name='Task',
            field=models.CharField(max_length=150),
        ),
    ]
