# Generated by Django 4.2.5 on 2023-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0008_alter_todo_priority_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Task',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
