# Generated by Django 4.2.5 on 2023-10-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0011_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Date',
            field=models.DateField(default='2001-05-05'),
            preserve_default=False,
        ),
    ]
