# Generated by Django 4.2.5 on 2023-10-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0010_alter_todo_priority_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.IntegerField(),
        ),
    ]
