# Generated by Django 4.2.5 on 2023-10-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0002_rename_priority_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.CharField(max_length=2),
        ),
    ]
