# Generated by Django 4.2.5 on 2023-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0004_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Task',
            field=models.TextField(),
        ),
    ]
