# Generated by Django 4.2.5 on 2023-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0006_remove_todo_name_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.TextField(),
        ),
    ]
