# Generated by Django 4.2.5 on 2023-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoapp', '0007_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Task',
            field=models.CharField(default='t', max_length=150, null=True),
        ),
    ]
