# Generated by Django 4.2.5 on 2023-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Img',
            field=models.ImageField(default=0, upload_to='gallary'),
            preserve_default=False,
        ),
    ]
